sudo: required
services: 
  - docker

before_install:
  - docker build -t Shantanu299/multi-docker-fibonacciCalculator -f ./client/Dockerfile.dev ./client

script:
  - docker run Shantanu299/multi-docker-fibonacciCalculator npm test -- --coverage

after_success:
  - docker build -t shantanu299/multi-client ./client
  - docker build -t shantanu299/multi-nginx ./nginx
  - docker build -t shantanu299/multi-server ./server
  - docker build -t shantanu299/multi-worker ./worker